# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_a1:
    has_velocity_limits: true
    max_velocity: 9.25024503557
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a2:
    has_velocity_limits: true
    max_velocity: 9.232791743050001
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a3:
    has_velocity_limits: true
    max_velocity: 9.389871375729999
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a4:
    has_velocity_limits: true
    max_velocity: 10.471975512
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a5:
    has_velocity_limits: true
    max_velocity: 10.471975512
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a6:
    has_velocity_limits: true
    max_velocity: 13.962634016
    has_acceleration_limits: false
    max_acceleration: 0